### ISSUE TITLE
Numbers are converted to string (yaml -> json)

### ISSUE THREAD

**Issue by sigmasoldi3r** [mircodezorzi/tojson#1]
Numbers are converted to string instead of preserving number type.

![image](https://user-images.githubusercontent.com/13834659/118556223-e796d800-b763-11eb-9936-40d9daac128f.png)

To:

![image](https://user-images.githubusercontent.com/13834659/118556184-dd74d980-b763-11eb-8174-edef2a466bef.png)

**Comment by mircodezorzi** [comment]
Fixed in #2. Thanks for the notice!
