### ISSUE TITLE
Runtime exception in json -> yaml when converting numbers

### ISSUE THREAD

**Issue by iaamp** [mircodezorzi/tojson#5]
When using the function `toyaml(const nlohmann::json &j, YAML::Emitter &e)` to convert a json object which contains numerals, the following exception occurs: `[json.exception.type_error.302] type must be string, but is number`.

This is likely because a numeral value cannot be obtained as string via `value().get<std::string>()`.

**Comment by iaamp** [comment]
I made a [pull request](https://github.com/mircodezorzi/tojson/pull/6) that should fix the issue. It works in my code, where i have embedded a slightly modified version of tojson (w/o xml to drop the dependency), but did not create any additional tests for it.

**Comment by SplitGemini** [comment]
Could you request together?
 
[#7](https://github.com/mircodezorzi/tojson/issues/7)

**Comment by mircodezorzi** [comment]
> w/o xml to drop the dependency

I guess it might be a good idea to add some compile-time flags to drop either XML or YAML support if not needed.
